# Generated by Django 4.0.4 on 2022-05-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_student_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='Id',
        ),
    ]
