# Generated by Django 4.0.4 on 2022-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_id_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
