# Generated by Django 4.0.4 on 2022-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_delete_superuser_alter_student_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dep',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
